"""Add user ingredients table

Revision ID: 022e0e0ecfa8
Revises: bb15664974e6
Create Date: 2024-05-11 22:53:44.697109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022e0e0ecfa8'
down_revision = 'bb15664974e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ingredients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ingredients')
    # ### end Alembic commands ###
