"""auto generate from models(should add vote table)

Revision ID: 2ad2d886faf4
Revises: a473a1e6a13a
Create Date: 2024-04-15 14:02:44.870128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad2d886faf4'
down_revision = 'a473a1e6a13a'
branch_labels = None
depends_on = None


# comanda folosita alembic revision --autogenerate -m "mesaj"
# alembic upgrade head

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
