"""Add relations between user and ingredients

Revision ID: bb558c3bb68e
Revises: 022e0e0ecfa8
Create Date: 2024-05-11 23:17:50.309381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb558c3bb68e'
down_revision = '022e0e0ecfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
